require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
Style/Documentation:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 10
Style/AsciiComments:
  Enabled: false