# frozen_string_literal: true

source 'https://rubygems.org'

group :test do
  gem 'rspec'
  gem 'rspec-collection_matchers'
end

group :development do
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rspec'
end
